<div>
    <div class="info-container">
        <h3>Basic string matching</h3>
        <div>
            Under basic string matching mode the matching will find any string
            that matches the provided query, this can be troublesome in the case
            of short queries that are usually found inside other words.
        </div>
        <h3>Regular expression matching</h3>
        <div>
            Regular expression matching is a lot more powerful at the cost of
            being substantially harder for the unintiatied, in this format your
            query is compiled to an
            <a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions"
                target="_blank"
            >
                ECMAscript Regular Expression
            </a>
            <br />
            Regular expressions can be used for matching only to a full word like
            the following:
            <code>/bword/b</code>
            <br />
            For more information on regular expressions consult the MDN documentation
            linked above.
        </div>
        <h3>Case sensitivity</h3>
        <div>
            With case sensitivity enabled only matches who follow the case of
            the inputted query will be matched, with case insensitivity the case
            of both the query and the captions is ignored, this is the advised
            way to deal with automatically generated captions as the
            capitalization generated by the speech-to-text crawlers can be
            unpredictable
        </div>
    </div>
</div>

<style lang="scss">
    .info-container {
        max-width: 50vw;
        margin: auto;
        * {
            text-align: start;
        }
        margin-bottom: 2em;
    }
    @media screen and (max-width: 800px) {
        .info-container {
            max-width: 70vw;
            * {
                text-align: center;
            }
        }
    }
</style>
